### ISSUE TITLE
Feature Request: allow only 1 participant

### ISSUE THREAD

**Issue by icnocop** [jwood/standup-timer#2]
I would like to request the ability to allow only 1 participant.

In this way, the app can be configured to only make one warning sound when there is 5 minutes left in the meeting for example in the case that the team does not do a round-robin type of stand-up meeting.

Thank you.

**Comment by jwood** [comment]
This should be pretty easy to do, along with your other request.  I'll try to find some time over the next week or two to make this change.

Thanks for the feedback.

**Comment by jwood** [comment]
Fixed in StandupTimer 1.3
